### PR TITLE
Fix profile update

### LINKED ISSUE #65: material-ui-color-bug
browser.js:49 Warning: Material-UI: The white color was not parsed correctly,
  because it has an unsupported format (color name or RGB %). This may cause issues in component rendering.

### PR DESCRIPTION
**Pull request by jacobooy**
- sending back updated token on profile update to reflect new information on all components
- nested ProfileForm component in ShowProfile to reflect updated name in the app drawer.
- further clean up of code incl stray rgb color codes

closes #65

### CODE REVIEW

File: server.js [hunk 1]
```diff
@@ -163,11 +163,23 @@ app.put('/api/profile', jwtAuth, (req, res) => {
     phone: req.body.phone,
     address: req.body.address
   };
-  User.findOneAndUpdate({email: email}, updateProfile, function(err) {
+  User.findOneAndUpdate({email: email}, updateProfile, { new: true}, function(err, updated) {
```
Comment (atreidesend) [inline server.js]: switch to promise approach

**Review by atreidesend — CHANGES_REQUESTED** [review]

**Review by atreidesend — APPROVED** [review]
